# pdiem M3 demo
#
# This demo environment will set up:
# - A single-node diem testnet
# - A cli to interact with diem testnet
# - A full Phala Network devopment network (phala-node, pruntime, phost) with pDiem deployed
# - A pdiem relayer

version: "3.9"
services:

  phala-node:
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - 9944:9944
      - 9933:9933
    entrypoint: [
      "/root/phala-node",
      "--dev", "--tmp", "--unsafe-ws-external"
    ]
  
  phala-pruntime:
    build:
      context: .
      dockerfile: pruntime.Dockerfile
    ports:
      - 8000:8000
    entrypoint: ["/bin/bash", "start_pruntime.sh"]
  
  phala-pherry:
    build:
      context: .
      dockerfile: pherry.Dockerfile
    depends_on:
      - phala-node
      - phala-pruntime
    environment: 
      - SLEEP_BEFORE_START=10
    restart: on-failure
    entrypoint: [
      "/root/pherry",
      "--dev",
      "--substrate-ws-endpoint=ws://phala-node:9944",
      "--pruntime-endpoint=http://phala-pruntime:8000",
    ]
  